// import type { Metadata } from "next";
// import { Fira_Code } from "next/font/google";
// import "./globals.css";
// import Navbar from "../components/Navbar";
// import { Provider } from "../utils/Provider";

// const firaCode = Fira_Code({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${firaCode.className} h-full bg-amber-50 text-indigo-950 dark:bg-slate-950 dark:text-amber-50 dark:selection:bg-purple-500`}
//       >
//         <Provider>
//           <Navbar />
//           <main className="h-full mx-auto max-w-5xl px-6">{children}</main>
//         </Provider>
//       </body>
//     </html>
//   );
// }

import Header from "../components/header";
import "./globals.css";
import { Inter } from "next/font/google";
import ActiveSectionContextProvider from "../context/active-section-context";
import Footer from "../components/footer";

import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Jana's Portfolio",
  description: "Jana is a full stack web developer and student at NIT Trichy.",
  icons:{
    icon: ["/favicon.ico?v=4"],
    apple: ["/apple-touch-icon.png?v=4"],
    shortcut: ["/apple-touch-icon.png"],
  },
  manifest: "/site.webmanifest",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body
        className={`${inter.className}  bg-gradient-to-r from-slate-900 via-purple-900 
            to-slate-900  relative pt-28 
            sm:pt-36 text-gray-50 `}
      >
        <ActiveSectionContextProvider>
          <Header />
          {children}
          <Footer />

          <Toaster position="top-right" />
        </ActiveSectionContextProvider>
      </body>
    </html>
  );
}
